### ISSUE TITLE
auth.exe problem

### ISSUE THREAD

**Issue by Neroli-realy** [wtfblub/NetspherePirates#121]
2017-02-05 18:38:50.2517|INFO|Program->Main:32|Checking database... 
2017-02-05 18:38:58.6541|INFO|Program->Main:38|Starting server... 
2017-02-05 18:39:00.0202|DEBUG|ProudServerPipe->OnStart:126|Initializing... 
2017-02-05 18:39:05.1125|ERROR|Program->OnUnhandledException:99|UnhandledException 
Nancy.Hosting.Self.AutomaticUrlReservationCreationFailureException: The Nancy self host was unable to start, as no namespace reservation existed for the provided url(s).

Please either enable UrlReservations.CreateAutomatically on the HostConfiguration provided to 
the NancyHost, or create the reservations manually with the (elevated) command(s):

netsh http add urlacl url="http://+:27000/" user="Everyone"

   at Nancy.Hosting.Self.NancyHost.StartListener()
   at Nancy.Hosting.Self.NancyHost.Start()
   at Netsphere.Program.Main() in C:\projects\netspherepirates\src\Auth\Program.cs:line 44

**Comment by wtfblub** [comment]
You have to start it as admin.

**Comment by Neroli-realy** [comment]
oh thanks works now 

can i edit the source?

i made some changes in some funcs

**Comment by BioAleks** [comment]
Pull requests are always welcome if you want to help.
