### ISSUE TITLE
Game.exe Problem

### ISSUE THREAD

**Issue by Shixyo** [wtfblub/NetspherePirates#153]
I'm not very literate with this kind of stuff, but I would like to host a private server for me and my buddies to mess around on from time to time. If anyone still frequents this, and can make heads of it, I'd appreciate it! I can log in, but when it gets to server selection and channels, there's nothing there.

2017-04-09 23:19:40.4862|INFO|Program->Main:33||Checking database... 
2017-04-09 23:19:45.9788|INFO|Program->FillShop:139||NoobMode: Filling the shop with items 
2017-04-09 23:19:49.1304|DEBUG|ResourceCache->GetChannels:72||Caching... 
2017-04-09 23:19:49.2570|ERROR|Program->OnUnhandledException:114||UnhandledException 
System.TypeInitializationException: The type initializer for 'Netsphere.Network.GameServer' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Fam\Desktop\S4P\game\data\xml\_eu_channel_setting.x7'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at Netsphere.Resource.ResourceLoader.Deserialize[T](String fileName) in C:\projects\netspherepirates\src\Game\Resource\ResourceLoader.cs:line 507
   at Netsphere.Resource.ResourceLoader.<LoadChannels>d__7.MoveNext() in C:\projects\netspherepirates\src\Game\Resource\ResourceLoader.cs:line 45
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Netsphere.Resource.ResourceCache.GetChannels() in C:\projects\netspherepirates\src\Game\Resource\ResourceCache.cs:line 76
   at Netsphere.Network.GameServer..ctor() in C:\projects\netspherepirates\src\Game\Network\GameServer.cs:line 159
   at Netsphere.Network.GameServer..cctor() in C:\projects\netspherepirates\src\Game\Network\GameServer.cs:line 30
   --- End of inner exception stack trace ---
   at Netsphere.Network.GameServer.get_Instance()
   at Netsphere.Program.FillShop() in C:\projects\netspherepirates\src\Game\Program.cs:line 198
   at Netsphere.Program.Main() in C:\projects\netspherepirates\src\Game\Program.cs:line 42
2017-04-09 23:24:05.4531|INFO|Program->Main:33||Checking database... 
2017-04-09 23:24:06.8812|INFO|Program->FillShop:139||NoobMode: Filling the shop with items 
2017-04-09 23:24:07.5382|DEBUG|ResourceCache->GetChannels:72||Caching... 
2017-04-09 23:24:07.5592|ERROR|Program->OnUnhandledException:114||UnhandledException 
System.TypeInitializationException: The type initializer for 'Netsphere.Network.GameServer' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Fam\Desktop\S4P\game\data\xml\_eu_channel_setting.x7'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at Netsphere.Resource.ResourceLoader.Deserialize[T](String fileName) in C:\projects\netspherepirates\src\Game\Resource\ResourceLoader.cs:line 507
   at Netsphere.Resource.ResourceLoader.<LoadChannels>d__7.MoveNext() in C:\projects\netspherepirates\src\Game\Resource\ResourceLoader.cs:line 45
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Netsphere.Resource.ResourceCache.GetChannels() in C:\projects\netspherepirates\src\Game\Resource\ResourceCache.cs:line 76
   at Netsphere.Network.GameServer..ctor() in C:\projects\netspherepirates\src\Game\Network\GameServer.cs:line 159
   at Netsphere.Network.GameServer..cctor() in C:\projects\netspherepirates\src\Game\Network\GameServer.cs:line 30
   --- End of inner exception stack trace ---
   at Netsphere.Network.GameServer.get_Instance()
   at Netsphere.Program.FillShop() in C:\projects\netspherepirates\src\Game\Program.cs:line 198
   at Netsphere.Program.Main() in C:\projects\netspherepirates\src\Game\Program.cs:line 42
2017-04-09 23:24:22.4917|INFO|Program->Main:33||Checking database... 
2017-04-09 23:24:23.9207|INFO|Program->FillShop:139||NoobMode: Filling the shop with items 
2017-04-09 23:24:24.5758|DEBUG|ResourceCache->GetChannels:72||Caching... 
2017-04-09 23:24:24.5968|ERROR|Program->OnUnhandledException:114||UnhandledException 
System.TypeInitializationException: The type initializer for 'Netsphere.Network.GameServer' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Fam\Desktop\S4P\game\data\xml\_eu_channel_setting.x7'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at Netsphere.Resource.ResourceLoader.Deserialize[T](String fileName) in C:\projects\netspherepirates\src\Game\Resource\ResourceLoader.cs:line 507
   at Netsphere.Resource.ResourceLoader.<LoadChannels>d__7.MoveNext() in C:\projects\netspherepirates\src\Game\Resource\ResourceLoader.cs:line 45
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Netsphere.Resource.ResourceCache.GetChannels() in C:\projects\netspherepirates\src\Game\Resource\ResourceCache.cs:line 76
   at Netsphere.Network.GameServer..ctor() in C:\projects\netspherepirates\src\Game\Network\GameServer.cs:line 159
   at Netsphere.Network.GameServer..cctor() in C:\projects\netspherepirates\src\Game\Network\GameServer.cs:line 30
   --- End of inner exception stack trace ---
   at Netsphere.Network.GameServer.get_Instance()
   at Netsphere.Program.FillShop() in C:\projects\netspherepirates\src\Game\Program.cs:line 198
   at Netsphere.Program.Main() in C:\projects\netspherepirates\src\Game\Program.cs:line 42
2017-04-09 23:25:03.4909|INFO|Program->Main:33||Checking database... 
2017-04-09 23:25:04.9030|INFO|Program->FillShop:139||NoobMode: Filling the shop with items 
2017-04-09 23:25:05.5590|DEBUG|ResourceCache->GetChannels:72||Caching... 
2017-04-09 23:25:05.5800|ERROR|Program->OnUnhandledException:114||UnhandledException 
System.TypeInitializationException: The type initializer for 'Netsphere.Network.GameServer' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Fam\Desktop\S4P\game\data\xml\_eu_channel_setting.x7'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at Netsphere.Resource.ResourceLoader.Deserialize[T](String fileName) in C:\projects\netspherepirates\src\Game\Resource\ResourceLoader.cs:line 507
   at Netsphere.Resource.ResourceLoader.<LoadChannels>d__7.MoveNext() in C:\projects\netspherepirates\src\Game\Resource\ResourceLoader.cs:line 45
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Netsphere.Resource.ResourceCache.GetChannels() in C:\projects\netspherepirates\src\Game\Resource\ResourceCache.cs:line 76
   at Netsphere.Network.GameServer..ctor() in C:\projects\netspherepirates\src\Game\Network\GameServer.cs:line 159
   at Netsphere.Network.GameServer..cctor() in C:\projects\netspherepirates\src\Game\Network\GameServer.cs:line 30
   --- End of inner exception stack trace ---
   at Netsphere.Network.GameServer.get_Instance()
   at Netsphere.Program.FillShop() in C:\projects\netspherepirates\src\Game\Program.cs:line 198
   at Netsphere.Program.Main() in C:\projects\netspherepirates\src\Game\Program.cs:line 42
2017-04-09 23:26:22.7176|INFO|Program->Main:33||Checking database... 
2017-04-09 23:26:24.1366|INFO|Program->FillShop:139||NoobMode: Filling the shop with items 
2017-04-09 23:26:24.7907|DEBUG|ResourceCache->GetChannels:72||Caching... 
2017-04-09 23:26:24.8117|ERROR|Program->OnUnhandledException:114||UnhandledException 
System.TypeInitializationException: The type initializer for 'Netsphere.Network.GameServer' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Fam\Desktop\S4P\game\data\xml\_eu_channel_setting.x7'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at Netsphere.Resource.ResourceLoader.Deserialize[T](String fileName) in C:\projects\netspherepirates\src\Game\Resource\ResourceLoader.cs:line 507
   at Netsphere.Resource.ResourceLoader.<LoadChannels>d__7.MoveNext() in C:\projects\netspherepirates\src\Game\Resource\ResourceLoader.cs:line 45
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Netsphere.Resource.ResourceCache.GetChannels() in C:\projects\netspherepirates\src\Game\Resource\ResourceCache.cs:line 76
   at Netsphere.Network.GameServer..ctor() in C:\projects\netspherepirates\src\Game\Network\GameServer.cs:line 159
   at Netsphere.Network.GameServer..cctor() in C:\projects\netspherepirates\src\Game\Network\GameServer.cs:line 30
   --- End of inner exception stack trace ---
   at Netsphere.Network.GameServer.get_Instance()
   at Netsphere.Program.FillShop() in C:\projects\netspherepirates\src\Game\Program.cs:line 198
   at Netsphere.Program.Main() in C:\projects\netspherepirates\src\Game\Program.cs:line 42
2017-04-09 23:26:30.9750|INFO|Program->Main:33||Checking database... 
2017-04-09 23:26:32.3991|INFO|Program->FillShop:139||NoobMode: Filling the shop with items 
2017-04-09 23:26:33.0461|DEBUG|ResourceCache->GetChannels:72||Caching... 
2017-04-09 23:26:33.0661|ERROR|Program->OnUnhandledException:114||UnhandledException 
System.TypeInitializationException: The type initializer for 'Netsphere.Network.GameServer' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Fam\Desktop\S4P\game\data\xml\_eu_channel_setting.x7'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at Netsphere.Resource.ResourceLoader.Deserialize[T](String fileName) in C:\projects\netspherepirates\src\Game\Resource\ResourceLoader.cs:line 507
   at Netsphere.Resource.ResourceLoader.<LoadChannels>d__7.MoveNext() in C:\projects\netspherepirates\src\Game\Resource\ResourceLoader.cs:line 45
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Netsphere.Resource.ResourceCache.GetChannels() in C:\projects\netspherepirates\src\Game\Resource\ResourceCache.cs:line 76
   at Netsphere.Network.GameServer..ctor() in C:\projects\netspherepirates\src\Game\Network\GameServer.cs:line 159
   at Netsphere.Network.GameServer..cctor() in C:\projects\netspherepirates\src\Game\Network\GameServer.cs:line 30
   --- End of inner exception stack trace ---
   at Netsphere.Network.GameServer.get_Instance()
   at Netsphere.Program.FillShop() in C:\projects\netspherepirates\src\Game\Program.cs:line 198
   at Netsphere.Program.Main() in C:\projects\netspherepirates\src\Game\Program.cs:line 42
2017-04-09 23:26:36.1407|INFO|Program->Main:33||Checking database... 
2017-04-09 23:26:37.5608|INFO|Program->FillShop:139||NoobMode: Filling the shop with items 
2017-04-09 23:26:38.2118|DEBUG|ResourceCache->GetChannels:72||Caching... 
2017-04-09 23:26:38.2328|ERROR|Program->OnUnhandledException:114||UnhandledException 
System.TypeInitializationException: The type initializer for 'Netsphere.Network.GameServer' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Fam\Desktop\S4P\game\data\xml\_eu_channel_setting.x7'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at Netsphere.Resource.ResourceLoader.Deserialize[T](String fileName) in C:\projects\netspherepirates\src\Game\Resource\ResourceLoader.cs:line 507
   at Netsphere.Resource.ResourceLoader.<LoadChannels>d__7.MoveNext() in C:\projects\netspherepirates\src\Game\Resource\ResourceLoader.cs:line 45
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Netsphere.Resource.ResourceCache.GetChannels() in C:\projects\netspherepirates\src\Game\Resource\ResourceCache.cs:line 76
   at Netsphere.Network.GameServer..ctor() in C:\projects\netspherepirates\src\Game\Network\GameServer.cs:line 159
   at Netsphere.Network.GameServer..cctor() in C:\projects\netspherepirates\src\Game\Network\GameServer.cs:line 30
   --- End of inner exception stack trace ---
   at Netsphere.Network.GameServer.get_Instance()
   at Netsphere.Program.FillShop() in C:\projects\netspherepirates\src\Game\Program.cs:line 198
   at Netsphere.Program.Main() in C:\projects\netspherepirates\src\Game\Program.cs:line 42

**Comment by FreeDenny9700** [comment]
Go to Netaphere Pirates folder -> src -> tools -> Data Extractor and put Data Extractor exe into S4 League Folder, run as administrator. After finishing, put "data" Folder into Game Folder and run Game.exe

**Comment by XXXTEMPTATION** [comment]
Can you please tell us whether this fixed your problem or not.

**Comment by Shixyo** [comment]
I haven't been able to do it yet, need to do a clear installation of windows on the desktop that I was trying this out on. I will post as soon as I get a chance to try it, some time tonight.



Sent via the Samsung Galaxy S® 6 edge, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by Shixyo** [comment]
It worked, though I had been confused for a bit. Apparently I had 2 different setups for private servers, and was putting things in the wrong folder. Thanks!
