### ISSUE TITLE
Disconnect when entering server

### ISSUE THREAD

**Issue by gabrielpop12** [wtfblub/NetspherePirates#162]
Hello, I wanted to know why I disconnected at the time of entering the server, pressing the server on the console throws me to start well and then appears a series of errors and returns me to choose the server

`2017-04-27 10:23:50.8412|DEBUG|GameServer:187| [tomomo<3>-User]|Disconnected 
2017-04-27 10:23:58.3556|INFO|AuthService:0| [tomomo<3>-User]|Login from 127.0.0.1:52979 
2017-04-27 10:23:58.4146|INFO|AuthService:0| [tomomo<3>-User]|Login success 
2017-04-27 10:23:58.4196|ERROR|GameServer:218| [tomomo<3>-User]| 
System.AggregateException: One or more errors occurred. ---> DotNetty.Codecs.EncoderException: Exception of type 'DotNetty.Codecs.EncoderException' was thrown. ---> System.TypeInitializationException: The type initializer for 'SharpLzo.miniLzo' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SharpLzo.Native.LzoNative' threw an exception. ---> System.Exception: The miniLzo native library failed to initialize
   at SharpLzo.Native.LzoNative..cctor()
   --- End of inner exception stack trace ---
   at SharpLzo.Native.LzoNative.get_Instance()
   at SharpLzo.miniLzo..cctor()
   --- End of inner exception stack trace ---
   at SharpLzo.miniLzo.Compress(Byte[] data)
   at Netsphere.Network.NetsphereExtensions.CompressLZO(Byte[] data) in C:\Users\Tomomo\Documents\S4 Server\NetspherePirates-master\src\Netsphere.Network\Extensions.cs:line 16
   at Netsphere.Network.Message.Game.SInventoryInfoAckMessage.Serializer.Serialize(BinaryWriter writer, SInventoryInfoAckMessage value) in C:\Users\Tomomo\Documents\S4 Server\NetspherePirates-master\src\Netsphere.Network\Message\Game\S2C.cs:line 167
   at _DynamicMethod28(BinaryWriter , Object )
   at BlubLib.Serialization.Serializer.Serialize(BinaryWriter writer, Object value)
   at ProudNet.Codecs.MessageEncoder.Encode(IChannelHandlerContext context, SendContext message, List`1 output) in C:\Users\Tomomo\Documents\S4 Server\NetspherePirates-master\src\ProudNet\Codecs\MessageEncoder.cs:line 38
   at DotNetty.Codecs.MessageToMessageEncoder`1.WriteAsync(IChannelHandlerContext ctx, Object msg)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Netsphere.Network.Services.AuthService.<LoginAsync>d__5.MoveNext() in C:\Users\Tomomo\Documents\S4 Server\NetspherePirates-master\src\Game\Network\Services\AuthService.cs:line 316
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Netsphere.Network.Services.AuthService.<LoginHandler>d__2.MoveNext() in C:\Users\Tomomo\Documents\S4 Server\NetspherePirates-master\src\Game\Network\Services\AuthService.cs:line 225
   --- End of inner exception stack trace ---
   at BlubLib.DotNetty.Handlers.MessageHandling.MessageHandler`1.<>c.<OnMessageReceived>b__5_0(Task task, Object _)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Netsphere.Network.FilteredMessageHandler`1.<OnMessageReceived>d__3.MoveNext() in C:\Users\Tomomo\Documents\S4 Server\NetspherePirates-master\src\Game\Network\FilteredMessageHandler.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BlubLib.DotNetty.Handlers.MessageHandling.SimpleMessageHandler.<ChannelRead>d__1.MoveNext()
---> (Inner Exception #0) DotNetty.Codecs.EncoderException: Exception of type 'DotNetty.Codecs.EncoderException' was thrown. ---> System.TypeInitializationException: The type initializer for 'SharpLzo.miniLzo' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SharpLzo.Native.LzoNative' threw an exception. ---> System.Exception: The miniLzo native library failed to initialize
   at SharpLzo.Native.LzoNative..cctor()
   --- End of inner exception stack trace ---
   at SharpLzo.Native.LzoNative.get_Instance()
   at SharpLzo.miniLzo..cctor()
   --- End of inner exception stack trace ---
   at SharpLzo.miniLzo.Compress(Byte[] data)
   at Netsphere.Network.NetsphereExtensions.CompressLZO(Byte[] data) in C:\Users\Tomomo\Documents\S4 Server\NetspherePirates-master\src\Netsphere.Network\Extensions.cs:line 16
   at Netsphere.Network.Message.Game.SInventoryInfoAckMessage.Serializer.Serialize(BinaryWriter writer, SInventoryInfoAckMessage value) in C:\Users\Tomomo\Documents\S4 Server\NetspherePirates-master\src\Netsphere.Network\Message\Game\S2C.cs:line 167
   at _DynamicMethod28(BinaryWriter , Object )
   at BlubLib.Serialization.Serializer.Serialize(BinaryWriter writer, Object value)
   at ProudNet.Codecs.MessageEncoder.Encode(IChannelHandlerContext context, SendContext message, List`1 output) in C:\Users\Tomomo\Documents\S4 Server\NetspherePirates-master\src\ProudNet\Codecs\MessageEncoder.cs:line 38
   at DotNetty.Codecs.MessageToMessageEncoder`1.WriteAsync(IChannelHandlerContext ctx, Object msg)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Netsphere.Network.Services.AuthService.<LoginAsync>d__5.MoveNext() in C:\Users\Tomomo\Documents\S4 Server\NetspherePirates-master\src\Game\Network\Services\AuthService.cs:line 316
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Netsphere.Network.Services.AuthService.<LoginHandler>d__2.MoveNext() in C:\Users\Tomomo\Documents\S4 Server\NetspherePirates-master\src\Game\Network\Services\AuthService.cs:line 225<---

2017-04-27 10:23:58.4196|ERROR|GameServer:218| [tomomo<3>-User]| 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ProudNet.Crypt'.
   at ProudNet.Crypt.Decrypt(Stream src, Stream dst, Boolean reliable) in C:\Users\Tomomo\Documents\S4 Server\NetspherePirates-master\src\ProudNet\Crypt.cs:line 44
   at ProudNet.Handlers.CoreHandler.EncryptedReliableMessage(IChannelHandlerContext context, ProudSession session, EncryptedReliableMessage message) in C:\Users\Tomomo\Documents\S4 Server\NetspherePirates-master\src\ProudNet\Handlers\CoreHandler.cs:line 69
   at EncryptedReliableMessage(Closure , MessageHandler`1 , IChannelHandlerContext , Object )
   at BlubLib.DotNetty.Handlers.MessageHandling.MessageHandler`1.OnMessageReceived(IChannelHandlerContext context, Object message)
   at BlubLib.DotNetty.Handlers.MessageHandling.SimpleMessageHandler.<ChannelRead>d__1.MoveNext()
2017-04-27 10:23:58.4356|DEBUG|GameServer:187| [tomomo<3>-User]|Disconnected `

**Comment by GameRaiderCC** [comment]
Which branch do you use?

**Comment by gabrielpop12** [comment]
@GameRaiderCC  What branch
If you talk about something inside the source, it is not touched anything or modified, I would not know to tell you.

**Comment by GameRaiderCC** [comment]
I mean do you use the patch26 version?

**Comment by gabrielpop12** [comment]
If I'm using the patch26 version

**Comment by BioAleks** [comment]
https://github.com/wtfblub/NetspherePirates/issues/165 
Same problem (but i can play, friend = disconnect).

**Comment by wtfblub** [comment]
You are missing one of the requirements.

**Comment by gabrielpop12** [comment]
@wtfblub I have all the requirements that it asks, is more, with the files 1184 normal enter, with the files season 1 I have the problem: P probe with another PC at the time and the same thing happened to me, there is a public server with these files, client of that server and there I can not enter the server, but I get to the server selection.

**Comment by gabrielpop12** [comment]
@wtfblub Today I take the time to test the new files with the requirement of .net and that if it works me perfect. Before you put .net files I was not working, or at least 1126.
P.D: I love the work that you are doing, that I am excited that some of the S4 community, however small it may be that you are concerned about fixing this game or that you at least try. I try to contribute in what I can always and spread their work.
