### ISSUE TITLE
what this?

### ISSUE THREAD

**Issue by s4archivos** [wtfblub/NetspherePirates#179]
Help me please!!
![18836554_1332873163462561_15413697_o](https://cloud.githubusercontent.com/assets/20717279/26658832/4b3069fa-4632-11e7-99ef-1d53510bc7f4.png)

-----
System.OverflowException: Arithmetic operation resulted in an overflow.
   at DotNetty.Transport.Channels.MultithreadEventLoopGroup..ctor(Func`2 eventLoopFactory, Int32 eventLoopCount)
   at DotNetty.Transport.Channels.MultithreadEventLoopGroup..ctor(Int32 eventLoopCount)
   at Netsphere.Program.Main() in E:\Server\NetspherePirates-master\src\Game\Program.cs:line 56

**Comment by BioAleks** [comment]
https://github.com/wtfblub/NetspherePirates/issues/164
