### ISSUE TITLE
name is  : Alfred John

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#191]
my facebook : 4lph4@apkmd.com
add me

**Comment by redapro** [comment]
game exe error
Log:
2017-07-05 16:16:57.5602|INFO|Program:37||Initializing...
2017-07-05 16:16:57.8070|INFO|AuthDatabase:286||Initializing...
2017-07-05 16:16:58.6485|INFO|GameDatabase:362||Initializing...
2017-07-05 16:17:07.3311|DEBUG|ResourceCache:56||Caching...
2017-07-05 16:17:09.2374|INFO|Program:53||Starting server...
2017-07-05 16:17:09.3693|ERROR|Program:111||UnhandledException
System.OverflowException: Arithmetic operation resulted in an overflow.
at DotNetty.Transport.Channels.MultithreadEventLoopGroup..ctor(Func`2 eventLoopFactory, Int32 eventLoopCount)
at DotNetty.Transport.Channels.MultithreadEventLoopGroup..ctor(Int32 eventLoopCount)
at Netsphere.Program.Main() in C:\Users\Unkown\Downloads\NetspherePirates-master\src\Game\Program.cs:line 56
