### ISSUE TITLE
Auth.exe Error when trying to put a server ip address or a hamachi ip address

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#193]
here is the log : 
2017-07-06 06:06:31.0996|INFO|AuthDatabase:109|Initializing... 
2017-07-06 06:06:33.5566|INFO|Program:39|Starting server... 
2017-07-06 06:06:40.1699|ERROR|Program:97|UnhandledException 
System.AggregateException: One or more errors occurred. ---> System.Net.Sockets.SocketException: The requested address is not valid in its context
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.DoBind(EndPoint localAddress)
   at DotNetty.Transport.Channels.AbstractChannel.AbstractUnsafe.BindAsync(EndPoint localAddress)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetty.Transport.Bootstrapping.AbstractBootstrap`2.<DoBindAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskExtensions.WaitEx[TResult](Task`1 this)
   at ProudNet.ProudServer.Listen(IPEndPoint tcpListener, IPAddress udpAddress, Int32[] udpListenerPorts, IEventLoopGroup listenerEventLoopGroup, IEventLoopGroup workerEventLoopGroup) in C:\Users\Unkown\Downloads\NetspherePirates-master\src\ProudNet\ProudServer.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.ExceptionExtensions.Rethrow(Exception this)
   at ProudNet.ProudServer.Listen(IPEndPoint tcpListener, IPAddress udpAddress, Int32[] udpListenerPorts, IEventLoopGroup listenerEventLoopGroup, IEventLoopGroup workerEventLoopGroup) in C:\Users\Unkown\Downloads\NetspherePirates-master\src\ProudNet\ProudServer.cs:line 153
   at Netsphere.Program.Main() in C:\Users\Unkown\Downloads\NetspherePirates-master\src\Auth\Program.cs:line 42
---> (Inner Exception #0) System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.DoBind(EndPoint localAddress)
   at DotNetty.Transport.Channels.AbstractChannel.AbstractUnsafe.BindAsync(EndPoint localAddress)<---

2017-07-06 06:07:07.7900|INFO|AuthDatabase:109|Initializing... 
2017-07-06 06:07:09.7099|INFO|Program:39|Starting server... 
2017-07-06 06:07:12.1894|ERROR|Program:97|UnhandledException 
System.AggregateException: One or more errors occurred. ---> System.Net.Sockets.SocketException: The requested address is not valid in its context
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.DoBind(EndPoint localAddress)
   at DotNetty.Transport.Channels.AbstractChannel.AbstractUnsafe.BindAsync(EndPoint localAddress)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetty.Transport.Bootstrapping.AbstractBootstrap`2.<DoBindAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskExtensions.WaitEx[TResult](Task`1 this)
   at ProudNet.ProudServer.Listen(IPEndPoint tcpListener, IPAddress udpAddress, Int32[] udpListenerPorts, IEventLoopGroup listenerEventLoopGroup, IEventLoopGroup workerEventLoopGroup) in C:\Users\Unkown\Downloads\NetspherePirates-master\src\ProudNet\ProudServer.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.ExceptionExtensions.Rethrow(Exception this)
   at ProudNet.ProudServer.Listen(IPEndPoint tcpListener, IPAddress udpAddress, Int32[] udpListenerPorts, IEventLoopGroup listenerEventLoopGroup, IEventLoopGroup workerEventLoopGroup) in C:\Users\Unkown\Downloads\NetspherePirates-master\src\ProudNet\ProudServer.cs:line 153
   at Netsphere.Program.Main() in C:\Users\Unkown\Downloads\NetspherePirates-master\src\Auth\Program.cs:line 42
---> (Inner Exception #0) System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.DoBind(EndPoint localAddress)
   at DotNetty.Transport.Channels.AbstractChannel.AbstractUnsafe.BindAsync(EndPoint localAddress)<---

**Comment by Mr-Sp1x3r** [comment]
Hamachi IP's Are Not supported anymore
tell your  brother that he can try the season 1 instead of trying shit with a "Testing Branch"
