### ISSUE TITLE
Unhandled Excepnion error

### ISSUE THREAD

**Issue by deah100gun** [wtfblub/NetspherePirates#195]
Hello Please help me. 

I create release the open sources of wich and run the auth this ok. Run the game.exe and error. Error the Game/Program.cs the line 56. 

This type of game.exe:

UnhandledException 
System.OverflowException: Array dimensions exceeded supported range.
   at DotNetty.Transport.Channels.MultithreadEventLoopGroup..ctor(Func`2 eventLoopFactory, Int32 eventLoopCount)
   at Netsphere.Program.Main() in C:\Users\Death99Gun\Downloads\Build\src\Game\Program.cs:line 56

**Comment by deah100gun** [comment]
I solved!

i open src/game/Config.cs and change WorkerThreads = 1;

**Comment by BioAleks** [comment]
https://github.com/wtfblub/NetspherePirates/commit/d39a76f27a1787c426e6bf8b59d309ff90a8fd3d
