### ISSUE TITLE
Error when trying to setup the Emu (which was before .NetCore Update) On A VPS

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#205]
I have a VPS ... I have put the address in hjson instead of 127.0.0.1...
I tried opening ports and tried turning off firewall but i have the same error

2017-09-01 16:28:41.5682|INFO|AuthDatabase:109|Initializing... 
2017-09-01 16:28:41.8935|INFO|Program:39|Starting server... 
2017-09-01 16:28:42.0458|ERROR|Program:97|UnhandledException 
System.AggregateException: One or more errors occurred. ---> System.Net.Sockets.SocketException: The requested address is not valid in its context
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.DoBind(EndPoint localAddress)
   at DotNetty.Transport.Channels.AbstractChannel.AbstractUnsafe.BindAsync(EndPoint localAddress)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNetty.Transport.Bootstrapping.AbstractBootstrap`2.<DoBindAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskExtensions.WaitEx[TResult](Task`1 this)
   at ProudNet.ProudServer.Listen(IPEndPoint tcpListener, IPAddress udpAddress, Int32[] udpListenerPorts, IEventLoopGroup listenerEventLoopGroup, IEventLoopGroup workerEventLoopGroup) in C:\Users\Administrator\Downloads\NetspherePirates-bd75e26e26e0dac5c547e847f1ea8f87fdea0c5b\src\ProudNet\ProudServer.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.ExceptionExtensions.Rethrow(Exception this)
   at ProudNet.ProudServer.Listen(IPEndPoint tcpListener, IPAddress udpAddress, Int32[] udpListenerPorts, IEventLoopGroup listenerEventLoopGroup, IEventLoopGroup workerEventLoopGroup) in C:\Users\Administrator\Downloads\NetspherePirates-bd75e26e26e0dac5c547e847f1ea8f87fdea0c5b\src\ProudNet\ProudServer.cs:line 153
   at Netsphere.Program.Main() in C:\Users\Administrator\Downloads\NetspherePirates-bd75e26e26e0dac5c547e847f1ea8f87fdea0c5b\src\Auth\Program.cs:line 42
---> (Inner Exception #0) System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.DoBind(EndPoint localAddress)
   at DotNetty.Transport.Channels.AbstractChannel.AbstractUnsafe.BindAsync(EndPoint localAddress)<---

**Comment by wtfblub** [comment]
Use 0.0.0.0 for listeners.

**Comment by redapro** [comment]
At First I get Relay Tunnel Error trying to start the game from another pc
Second i get endpoint error when i put vps ip

**Comment by Mr-Sp1x3r** [comment]
Just open the required ports in the vps in order to get connections from other pc's

**Comment by redapro** [comment]
As I mentioned before , I opened the required ports....Same error
Turned OFF The Firewall...Same
Also when i put vps ip in end point ..this error appears in game console while saving players but it doesn't stop the emu :
2017-09-01 20:04:29.5033|ERROR|ServerlistManager:127||Failed to connect authserver on endpoint *****myip:27000. Retrying on next update.

**Comment by Mr-Sp1x3r** [comment]
Maybe...
You should put 127.0.0.1 In the Endpoint IP cuz its a local thing you know like it should be the ip of where the operation of relating the auth and the game server
so yeah,put 127.0.0.1 as an endpoint ip in both auth.hjson and game.hjson
And it would work ISH

**Comment by redapro** [comment]
Also,Tried 127.0.0.1 yesterday but same Relay Tunnel Error
