### ISSUE TITLE
Every 5 minutes players get a Relay Tunnel Error

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#209]
Here  is the log which follows a relay tunnel  error
DotNetty.Codecs.DecoderException: Exception of type 'DotNetty.Codecs.DecoderException' was thrown. ---> System.IndexOutOfRangeException: index: 96 (expected: range(0, 96)
   at DotNetty.Buffers.AbstractByteBuffer.CheckIndex(Int32 index)
   at DotNetty.Buffers.AbstractByteBuffer.GetByte(Int32 index)
   at DotNetty.Buffers.SwappedByteBuffer.GetByte(Int32 index)
   at ProudNet.Codecs.ProudFrameDecoder.GetUnadjustedFrameLength(IByteBuffer buffer, Int32 offset, Int32 length, ByteOrder order) in C:\Users\Administrator\Downloads\NetspherePirates-bd75e26e26e0dac5c547e847f1ea8f87fdea0c5b\src\ProudNet\Codecs\ProudFrameDecoder.cs:line 20
   at BlubLib.DotNetty.Codecs.LengthFieldBasedFrameDecoder.Decode(IChannelHandlerContext context, IByteBuffer input)
   at BlubLib.DotNetty.Codecs.LengthFieldBasedFrameDecoder.Decode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   at DotNetty.Codecs.ByteToMessageDecoder.CallDecode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   --- End of inner exception stack trace ---
   at DotNetty.Codecs.ByteToMessageDecoder.CallDecode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   at DotNetty.Codecs.ByteToMessageDecoder.ChannelRead(IChannelHandlerContext context, Object message)
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeChannelRead(Object msg)
2017-09-06 00:11:53.0062|ERROR|RelayServer:66|| 
DotNetty.Codecs.DecoderException: Exception of type 'DotNetty.Codecs.DecoderException' was thrown. ---> System.IndexOutOfRangeException: index: 96 (expected: range(0, 96)
   at DotNetty.Buffers.AbstractByteBuffer.CheckIndex(Int32 index)
   at DotNetty.Buffers.AbstractByteBuffer.GetByte(Int32 index)
   at DotNetty.Buffers.SwappedByteBuffer.GetByte(Int32 index)
   at ProudNet.Codecs.ProudFrameDecoder.GetUnadjustedFrameLength(IByteBuffer buffer, Int32 offset, Int32 length, ByteOrder order) in C:\Users\Administrator\Downloads\NetspherePirates-bd75e26e26e0dac5c547e847f1ea8f87fdea0c5b\src\ProudNet\Codecs\ProudFrameDecoder.cs:line 20
   at BlubLib.DotNetty.Codecs.LengthFieldBasedFrameDecoder.Decode(IChannelHandlerContext context, IByteBuffer input)
   at BlubLib.DotNetty.Codecs.LengthFieldBasedFrameDecoder.Decode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   at DotNetty.Codecs.ByteToMessageDecoder.CallDecode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   --- End of inner exception stack trace ---
   at DotNetty.Codecs.ByteToMessageDecoder.ChannelInactive(IChannelHandlerContext ctx)
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeChannelInactive()
2017-09-06 00:11:53.0081|DEBUG|GameServer:187| [dragonman225<27>-User]|Disconnected

**Comment by iBreak97** [comment]
Change from TCP to UDP in Game.hjson

**Comment by wtfblub** [comment]
Duplicate #165

**Comment by redapro** [comment]
How to change from tcp to udp?
i tried but i'm getting an error

**Comment by iBreak97** [comment]
you must use Array for example :

["port1", "port2", "port3"]
or only ["port1"]

**Comment by redapro** [comment]
I Chose Port 22000...Are You sure that this will fix this prob?
Thank You ;)

**Comment by iBreak97** [comment]
for me It fix problem

**Comment by redapro** [comment]
That's right or no ? 
 listener: 0.0.0.0:28003
  listener_chat: 0.0.0.0:28004
  listener_relay: 0.0.0.0:28005
  listener_relay_udp_ports: ["22000" ,"23000" , "24000"]
  listener_threads: 1
  worker_threads: 1
  player_limit: 10000
  security_level: 0

**Comment by iBreak97** [comment]
yes

**Comment by redapro** [comment]
With One Port There is some lag due to p2p and with 3 ports game gives a relay tunnel  error when i start a match
