### ISSUE TITLE
Big server close delay (auth and game server)

### ISSUE THREAD

**Issue by BioAleks** [wtfblub/NetspherePirates#220]
Hello.
Problem for Auth and Game server.
Server (old build have same problem) say in chat "Closing..." (closing server) 2 times and have close delay. 
When closing game server - server no stop save game and people can play, buy items and etc.
When close auth server - same problem (and people can connect).

**(Game server) Log:**
```
017-09-15 19:54:53.982 +03:00 [Information] Login from "134.249.178.148:54352"
2017-09-15 19:54:53.988 +03:00 [Information] Login success
2017-09-15 19:55:02.980 +03:00 [Information] Closing...
2017-09-15 19:55:02.982 +03:00 [Information] Closing...
2017-09-15 19:55:09.516 +03:00 [Information] Selecting character 1
2017-09-15 19:55:10.450 +03:00 [Information] Selecting character 2
2017-09-15 19:55:11.521 +03:00 [Information] Selecting character 0
2017-09-15 19:55:17.359 +03:00 [Information] Saving players...
2017-09-15 19:55:17.641 +03:00 [Information] Saving players completed
```
**(Auth server) Error (after close game server):**
```
2017-09-15 19:55:33.174 +03:00 [Error] Unhandled exception
System.Net.Sockets.SocketException (0x80004005): The remote host forcibly broke the existing connection
   at DotNetty.Transport.Channels.Sockets.SocketChannelAsyncOperation.Validate()
   at DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
2017-09-15 19:56:06.709 +03:00 [Information] Removed server Black Sword Netsphere 1139(1)
```
**(Auth server) log (when close server):**
```
2017-09-15 19:57:19.658 +03:00 [Information] Closing...
2017-09-15 19:57:19.660 +03:00 [Information] Closing...
2017-09-15 19:57:24.284 +03:00 [Debug] Login from 192.168.1.10 with username bioaleks
2017-09-15 19:57:24.455 +03:00 [Information] Login success for bioaleks
```

As you see - people can do anything (connect, buy items, change characters, play, etc) when server closing. 
Closing time (for me): 15 seconds (auth server)
game server - 30 seconds.

**Comment by BioAleks** [comment]
```
2017-09-15 19:55:33.174 +03:00 [Error] Unhandled exception
System.Net.Sockets.SocketException (0x80004005): The remote host forcibly broke the existing connection
   at DotNetty.Transport.Channels.Sockets.SocketChannelAsyncOperation.Validate()
   at DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
2017-09-15 19:56:06.709 +03:00 [Information] Removed server Black Sword Netsphere 1139(1)
```

This error _(auth server)_ did not disappear in the last build.
