### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AbDoShTa** [wtfblub/NetspherePirates#234]
Can Help Me
NetspherePirates Patch 1184

C:\Users\Allam>dotnet run --project src/Game
C:\Users\Allam\src\Game\Game.csproj : warning NU1701: Package 'Expressmapper 1.9
.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project tar
get framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatib
le with your project.
C:\Users\Allam\src\Game\Game.csproj : warning NU1701: Package 'Expressmapper 1.9
.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project tar
get framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatib
le with your project.
[Information ] Initializing...
[Information AuthDatabase] Initializing...
[Information GameDatabase] Initializing...
[Debug ResourceCache] Caching...
[Information ] Starting server...
[Error ] UnhandledException
System.OverflowException: Arithmetic operation resulted in an overflow.
   at DotNetty.Transport.Channels.MultithreadEventLoopGroup..ctor(Func`2 eventLo
opFactory, Int32 eventLoopCount)
   at DotNetty.Transport.Channels.MultithreadEventLoopGroup..ctor(Int32 eventLoo
pCount)
   at Netsphere.Program.Main() in C:\Users\Allam\src\Game\Program.cs:line 64

Unhandled Exception: System.OverflowException: Arithmetic operation resulted in
an overflow.
   at DotNetty.Transport.Channels.MultithreadEventLoopGroup..ctor(Func`2 eventLo
opFactory, Int32 eventLoopCount)
   at DotNetty.Transport.Channels.MultithreadEventLoopGroup..ctor(Int32 eventLoo
pCount)
   at Netsphere.Program.Main() in C:\Users\Allam\src\Game\Program.cs:line 64

**Comment by AbDoShTa** [comment]
help me please

**Comment by GameRaiderCC** [comment]
Please dont post issues about branch 1184
