### ISSUE TITLE
Disconnect Error i need help :3

### ISSUE THREAD

**Issue by handsomebananax** [wtfblub/NetspherePirates#252]
2018-01-20 12:39:43.6840|ERROR|RelayServer:66| [admin1<4>-User]| 
DotNetty.Codecs.DecoderException: Exception of type 'DotNetty.Codecs.DecoderException' was thrown. ---> System.IndexOutOfRangeException: index: 80 (expected: range(0, 80)
   at DotNetty.Buffers.AbstractByteBuffer.CheckIndex(Int32 index)
   at DotNetty.Buffers.AbstractByteBuffer.GetByte(Int32 index)
   at DotNetty.Buffers.SwappedByteBuffer.GetByte(Int32 index)
   at ProudNet.Codecs.ProudFrameDecoder.GetUnadjustedFrameLength(IByteBuffer buffer, Int32 offset, Int32 length, ByteOrder order) in C:\projects\netspherepirates\src\ProudNet\Codecs\ProudFrameDecoder.cs:line 20
   at BlubLib.DotNetty.Codecs.LengthFieldBasedFrameDecoder.Decode(IChannelHandlerContext context, IByteBuffer input)
   at BlubLib.DotNetty.Codecs.LengthFieldBasedFrameDecoder.Decode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   at DotNetty.Codecs.ByteToMessageDecoder.CallDecode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   --- End of inner exception stack trace ---
   at DotNetty.Codecs.ByteToMessageDecoder.CallDecode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   at DotNetty.Codecs.ByteToMessageDecoder.ChannelRead(IChannelHandlerContext context, Object message)
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeChannelRead(Object msg)
2018-01-20 12:39:43.7120|ERROR|RelayServer:66|| 
DotNetty.Codecs.DecoderException: Exception of type 'DotNetty.Codecs.DecoderException' was thrown. ---> System.IndexOutOfRangeException: index: 80 (expected: range(0, 80)
   at DotNetty.Buffers.AbstractByteBuffer.CheckIndex(Int32 index)
   at DotNetty.Buffers.AbstractByteBuffer.GetByte(Int32 index)
   at DotNetty.Buffers.SwappedByteBuffer.GetByte(Int32 index)
   at ProudNet.Codecs.ProudFrameDecoder.GetUnadjustedFrameLength(IByteBuffer buffer, Int32 offset, Int32 length, ByteOrder order) in C:\projects\netspherepirates\src\ProudNet\Codecs\ProudFrameDecoder.cs:line 20
   at BlubLib.DotNetty.Codecs.LengthFieldBasedFrameDecoder.Decode(IChannelHandlerContext context, IByteBuffer input)
   at BlubLib.DotNetty.Codecs.LengthFieldBasedFrameDecoder.Decode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   at DotNetty.Codecs.ByteToMessageDecoder.CallDecode(IChannelHandlerContext context, IByteBuffer input, List`1 output)
   --- End of inner exception stack trace ---
   at DotNetty.Codecs.ByteToMessageDecoder.ChannelInactive(IChannelHandlerContext ctx)
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeChannelInactive()
2018-01-20 12:39:43.7385|DEBUG|GameServer:187| [admin1<4>-User]|Disconnected

**Comment by Demon0no** [comment]
How about you tell us what you are doing, when you get that error?

**Comment by handsomebananax** [comment]
when we are playing st2  my friend disconnect from server after 5 min
