### ISSUE TITLE
Error When starting Game.exe(As admin)Important!

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#42]
Help!
(Also I need s4l eu dss file,etc(resources)like mach3 and other sets to be replaced)
(Also When will you finish the stable project?)
**# Old projects were working smoothly but latest project give me an error here is the log:**
2016-08-14 02:27:54.3489|INFO|Program->Main:34||Checking database... 
2016-08-14 02:28:02.0466|INFO|Program->FillShop:140||NoobMode: Filling the shop with items 
2016-08-14 02:28:03.5910|DEBUG|ResourceCache->GetChannels:72||Caching... 
2016-08-14 02:28:04.1838|ERROR|Program->OnUnhandledException:115||UnhandledException 
System.TypeInitializationException: The type initializer for 'Netsphere.Network.GameServer' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Reda\Downloads\NetspherePirates-master\src\Game\bin\Debug\data\xml\_eu_channel_setting.x7'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at Netsphere.Resource.ResourceLoader.Deserialize[T](String fileName) in C:\Users\Reda\Downloads\NetspherePirates-master\src\Game\Resource\ResourceLoader.cs:line 507
   at Netsphere.Resource.ResourceLoader.<LoadChannels>d__7.MoveNext() in C:\Users\Reda\Downloads\NetspherePirates-master\src\Game\Resource\ResourceLoader.cs:line 45
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Netsphere.Resource.ResourceCache.GetChannels() in C:\Users\Reda\Downloads\NetspherePirates-master\src\Game\Resource\ResourceCache.cs:line 76
   at Netsphere.Network.GameServer..ctor() in C:\Users\Reda\Downloads\NetspherePirates-master\src\Game\Network\GameServer.cs:line 159
   at Netsphere.Network.GameServer..cctor() in C:\Users\Reda\Downloads\NetspherePirates-master\src\Game\Network\GameServer.cs:line 30
   --- End of inner exception stack trace ---
   at Netsphere.Network.GameServer.get_Instance()
   at Netsphere.Program.FillShop() in C:\Users\Reda\Downloads\NetspherePirates-master\src\Game\Program.cs:line 199
   at Netsphere.Program.Main() in C:\Users\Reda\Downloads\NetspherePirates-master\src\Game\Program.cs:line 43

**Comment by FreeDenny9700** [comment]
Compile Wtfblub source, take Data Extractor and put this into s4 League folder, open DE and wait. After some seconds, you have a folder called Data. Put this folder into Game (server) folder and open Game.exe
Sorry for my bad english bro

**Comment by Saitama-Kun** [comment]
#redapro Iam Rabie Hedfi!
As Denny9700 Said !  : Make sure that the folder named data(extract it  from Fumbiclient By Blub's Dataextractor) Is In The same Game.exe folder!

**Comment by wtfblub** [comment]
Read the setup guide [here](https://github.com/wtfblub/NetspherePirates/wiki/Setup-from-a-pre-built-package)

**Comment by redapro** [comment]
Thanks
#Fixed
