### ISSUE TITLE
Important Error

### ISSUE THREAD

**Issue by redapro** [wtfblub/NetspherePirates#45]
Latest Server Files when  i start  auth and  game exe i face an error.However , old versions working..
When I Delete db game and auth sql files .the auth and game  servers open normally for first time but just restart them they will face these errors:
Auth Error at start  :
2016-08-16 15:37:07.9003|INFO|Program->Main:33|Checking database... 
2016-08-16 15:37:08.9934|ERROR|Program->OnUnhandledException:100|UnhandledException 
System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
table "accounts" already exists
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Shaolinq.Persistence.SqlDatabaseSchemaManager.CreateDatabaseSchema(Expression dataDefinitionExpressions, DatabaseCreationOptions options)
   at Shaolinq.Persistence.SqlDatabaseSchemaManager.CreateDatabaseAndSchema(DatabaseCreationOptions options)
   at Shaolinq.DataAccessModel.Create(DatabaseCreationOptions options)
   at Shaolinq.DataAccessModel.CreateIfNotExist()
   at Netsphere.Program.Main() in E:\Private Server\Sources+Game\NetspherePirates-master\src\Auth\Program.cs:line 37
2016-08-16 15:37:35.2483|INFO|Program->Main:33|Checking database... 
2016-08-16 15:37:37.3424|INFO|Program->Main:39|Starting server... 
2016-08-16 15:37:37.8385|DEBUG|ProudServerPipe->OnStart:126|Initializing... 
2016-08-16 15:37:41.6694|INFO|Program->Main:47|Ready for connections! 
2016-08-16 15:37:41.6694|WARN|Program->Main:53|!!! NOOB MODE IS ENABLED! EVERY LOGIN SUCCEEDS AND OVERRIDES ACCOUNT LOGIN DETAILS !!! 
2016-08-16 15:38:36.0924|INFO|ServerManager->Add:45|Added server Netsphere(1) 
2016-08-16 15:39:13.7676|INFO|ServerManager->Remove:85|Removed server Netsphere(1) 
2016-08-16 15:45:10.8447|INFO|Program->Main:33|Checking database... 
2016-08-16 15:45:11.6091|ERROR|Program->OnUnhandledException:100|UnhandledException 
System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
table "accounts" already exists
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Shaolinq.Persistence.SqlDatabaseSchemaManager.CreateDatabaseSchema(Expression dataDefinitionExpressions, DatabaseCreationOptions options)
   at Shaolinq.Persistence.SqlDatabaseSchemaManager.CreateDatabaseAndSchema(DatabaseCreationOptions options)
   at Shaolinq.DataAccessModel.Create(DatabaseCreationOptions options)
   at Shaolinq.DataAccessModel.CreateIfNotExist()
   at Netsphere.Program.Main() in E:\Private Server\Sources+Game\NetspherePirates-master\src\Auth\Program.cs:line 37

--------------------------------------------
Game Error : 
2016-08-16 15:38:05.9187|INFO|Program->Main:34||Checking database... 
2016-08-16 15:38:07.3998|ERROR|Program->OnUnhandledException:115||UnhandledException 
System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
table "accounts" already exists
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Shaolinq.Persistence.SqlDatabaseSchemaManager.CreateDatabaseSchema(Expression dataDefinitionExpressions, DatabaseCreationOptions options)
   at Shaolinq.Persistence.SqlDatabaseSchemaManager.CreateDatabaseAndSchema(DatabaseCreationOptions options)
   at Shaolinq.DataAccessModel.Create(DatabaseCreationOptions options)
   at Shaolinq.DataAccessModel.CreateIfNotExist()
   at Netsphere.Program.Main() in E:\Private Server\Sources+Game\NetspherePirates-master\src\Game\Program.cs:line 38
2016-08-16 15:38:44.7699|INFO|Program->Main:34||Checking database... 
2016-08-16 15:38:45.6560|ERROR|Program->OnUnhandledException:115||UnhandledException 
System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
table "accounts" already exists
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Shaolinq.Persistence.SqlDatabaseSchemaManager.CreateDatabaseSchema(Expression dataDefinitionExpressions, DatabaseCreationOptions options)
   at Shaolinq.Persistence.SqlDatabaseSchemaManager.CreateDatabaseAndSchema(DatabaseCreationOptions options)
   at Shaolinq.DataAccessModel.Create(DatabaseCreationOptions options)
   at Shaolinq.DataAccessModel.CreateIfNotExist()
   at Netsphere.Program.Main() in E:\Private Server\Sources+Game\NetspherePirates-master\src\Game\Program.cs:line 38
2016-08-16 15:45:56.1777|INFO|Program->Main:34||Checking database... 
2016-08-16 15:45:57.0201|ERROR|Program->OnUnhandledException:115||UnhandledException 
System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
table "accounts" already exists
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Shaolinq.Persistence.SqlDatabaseSchemaManager.CreateDatabaseSchema(Expression dataDefinitionExpressions, DatabaseCreationOptions options)
   at Shaolinq.Persistence.SqlDatabaseSchemaManager.CreateDatabaseAndSchema(DatabaseCreationOptions options)
   at Shaolinq.DataAccessModel.Create(DatabaseCreationOptions options)
   at Shaolinq.DataAccessModel.CreateIfNotExist()
   at Netsphere.Program.Main() in E:\Private Server\Sources+Game\NetspherePirates-master\src\Game\Program.cs:line 38

**Comment by redapro** [comment]
Solution????

**Comment by FreeDenny9700** [comment]
Use MySQL, no SQLite

**Comment by wtfblub** [comment]
What do you mean with latest version? Latest source or latest release package?

**Comment by redapro** [comment]
Source...Debugged made everything as i was making before ...In the first open it opened normally in the second time  it opened with an error ..I have to delete db files to open game + auth normally (they put them again )after putting them i restart then i face sql database error......
