### ISSUE TITLE
System.TypeInitializationException (Game server OnError:206)

### ISSUE THREAD

**Issue by DimitriuAdri** [wtfblub/NetspherePirates#54]
I don't know if this problem appear before. Sorry if it is duplicated.

When I try to open the server in another PC with the same server files that I used, it throw this error in gameserver: 

________________________________________________________________________________________________________________

2016-08-21 14:43:55.0354|ERROR|GameServer->OnError:206|| 
System.TypeInitializationException: The type initializer for 'SharpLzo.miniLzo' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SharpLzo.Native.LzoNative' threw an exception. ---> System.Exception: The miniLzo native library failed to initialize
   at SharpLzo.Native.LzoNative..cctor()
   --- End of inner exception stack trace ---
   at SharpLzo.Native.LzoNative.get_Instance()
   at SharpLzo.miniLzo..cctor()
   --- End of inner exception stack trace ---
   at SharpLzo.miniLzo.Compress(Byte[] data)
   at Netsphere.Network.NetsphereExtensions.CompressLZO(Byte[] data) in C:\NetspherePirates-master\src\Netsphere.Network\Extensions.cs:line 16
   at Netsphere.Network.Message.Game.SInventoryInfoAckMessage.Serializer.Serialize(BinaryWriter writer, SInventoryInfoAckMessage value) in C:\NetspherePirates-master\src\Netsphere.Network\Message\Game\S2C.cs:line 153
   at BlubLib.Serialization.Serializer.Serialize[T](BinaryWriter writer, T value)
   at BlubLib.Serialization.Serializer.Serialize(BinaryWriter writer, Object value)
   at Netsphere.Network.Message.GameMessage.Serialize(Stream stream) in C:\NetspherePirates-master\src\Netsphere.Network\Message\NetsphereMessage.cs:line 46
   at BlubLib.Network.Message.MessageExtensions.ToArray(IMessage message)
   at ProudNet.ProudPipe.ProcessAndSendMessage(MessageEventArgs e, EncryptContext context) in C:\NetspherePirates-master\src\ProudNet\ProudPipe.cs:line 122
   at ProudNet.ProudServerPipe.<OnSendMessage>d__17.MoveNext() in C:\NetspherePirates-master\src\ProudNet\ProudServerPipe.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BlubLib.Network.Session.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at ProudNet.ProudSession.<SendAsync>d__45.MoveNext() in C:\NetspherePirates-master\src\ProudNet\ProudSession.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Netsphere.Network.Services.AuthService.<LoginAsync>d__5.MoveNext() in C:\NetspherePirates-master\src\Game\Network\Services\AuthService.cs:line 310
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Netsphere.Network.Services.AuthService.<LoginHandler>d__2.MoveNext() in C:\NetspherePirates-master\src\Game\Network\Services\AuthService.cs:line 205
2016-08-21 14:43:55.0574|DEBUG|ProudPipe->OnDisconnected:79||Client 1000 disconnected 

_____________________________________________________________________________________________________________

Thanks for help :+1:

**Comment by DimitriuAdri** [comment]
Solved, only download the server again XD
